theme: jekyll-theme-chirpy
lang: en

# Site settings
title: "Jaspreet Kaur Bhamra"
tagline: "Data Scientist | ML Engineer | Human"
description: >-
  Maybe another way to connect with the world?

url: "https://jaspreetbhamra.github.io"
baseurl: ""   # important for user site

# Theme settings
theme_mode: dark   # light, dark, or auto

# Author info
author:
  name: "Jaspreet Kaur Bhamra"
  email: "your-noreply-email@users.noreply.github.com"
  avatar: "/assets/img/avatar.png"   # optional - add your photo here

# Navbar links
nav:
  - title: "Resume"
    url: /resume/
  - title: "Experience"
    url: /experience/
  - title: "Projects"
    url: /projects/
  # - title: "Human"
  #   url: /human/
  # - title: "Blog"
  #   url: /posts/
  # - title: "Google Scholar"
  #   url: "https://scholar.google.com/citations?user=YOUR_ID"

# Social media links
social:
  github: https://github.com/jaspreetbhamra
  linkedin: https://www.linkedin.com/in/jaspreet-kaur-bhamra/
  twitter: https://twitter.com/jaspreet_kaur13
  # if you want email icon in footer:
  email: jbhamra24@gmail.com
  scholar: https://scholar.google.com/citations?user=xwU4PZsAAAAJ&hl=en

# Footer
footer:
  copyright: "© 2025 Jaspreet Kaur Bhamra"
  since: 2025

# Plugins (default for Chirpy)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 10
